server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parkiran
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

